GET localhost:3000/api/users/sample
####
GET localhost:3000/api/users/eko
###
####
GET localhost:3000/api/users/hello?name=eko
####
GET localhost:3000/api/users/hello?first_name=eko&last_name=kanedy
####
GET localhost:3000/api/users/sample-response
####
GET localhost:3000/api/users/redirect
####
GET localhost:3000/api/users/hola
####
GET localhost:3000/api/users/connection
####
POST localhost:3000/api/users/create
content-type:application/json

{
  "firstName": "brian",
  "lastName": "prayetno"
}

### error
POST localhost:3000/api/users/create
content-type:application/json

{
  "firstName": null,
  "lastName": "prayetno"
}
